---
title: "DA3_Assignment2_AJK"
author: "Adam Kovacs"
date: "1/28/2022"
output: 
  pdf_document:
      fig_caption: true
      latex_engine: xelatex
header-includes: |
  \usepackage{titling}
  \setlength{\droptitle}{-8em}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, eval = TRUE)
```

### Introduction

In this project, I analyze the [****](link) to build predictive models 



```{r import}
#clear memory
rm(list=ls())

#import packages
if (!require(pacman)){
  install.packages("pacman")
}

pacman::p_load(tidyverse, caret, skimr, grid, glmnet, cowplot, modelsummary, fixest, naniar, stringr)

# import data
data <- read_csv("./data/listings.csv") %>% 
  mutate_if(is.character, factor)

```


```{r filtering data}

#filter on 2-6 guests
data <- data %>%
  filter(accommodates %in% seq(2,6,1))

#datasummary(property_type ~ N + Percent(), data = data )
data <- data %>%
  filter(property_type %in% c("Entire rental unit", "Entire serviced apartment",
                              "Entire home/apt", "Private room in rental unit", 
                              "Private room in serviced apartment","Room in rental unit","Room in serviced apartment", "Shared room in rental unit"))

#these are the categories fitting apartments 

#rename variables, create property type as factor
data <- data %>%
  mutate(
    property_type = ifelse(data$property_type %in% c("Entire rental unit", "Entire serviced apartment", "Entire home/apt"), "Entire apartment", "Room in apartment"),
    f_property_type = factor(property_type))

#datasummary(room_type ~ N + Percent() , data = data )

#there are some hotel rooms - need to be dropped

data <- data %>%
  filter (!room_type %in% c("Hotel room"))

```


```{r feature engineering}

#create room type as factor
data$f_room_type <- factor(ifelse(data$room_type== "Entire home/apt", "Entire/Apt",
                                   ifelse(data$room_type== "Private room", "Private",
                                          ifelse(data$room_type== "Shared room", "Shared", "."))))

#create host response time as categorical - first deal with two ways enoded NA
data <- data %>% naniar::replace_with_na(replace = list(host_response_time = 'N/A'))

data <- data %>%
  mutate(f_host_response_time = factor(host_response_time))

#create neighborhood_cleansed as factor - 367 levels
data <- data %>%
  mutate(f_neighbourhood_cleansed = factor(neighbourhood_cleansed))

#create numeric columns
data <- data %>%
  mutate(
    usd_price_day = as.numeric(price),
    p_host_response_rate = as.numeric(host_response_rate),
    p_host_acceptance_rate = as.numeric(host_acceptance_rate),
    c_host_listings_count = as.numeric(host_listings_count)
  )

#deal with bathrooms text - create numeric and factor variable from it
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

bathrooms_nr = numextract(data$bathrooms_text)

data <- data %>%
     mutate(bathrooms = as.numeric(numextract(bathrooms_text)), 
            bathroom_type = str_trim(str_split_fixed(data$bathrooms_text, bathrooms_nr, n=2)[,2]))

data <- data %>%
     mutate(bathroom_type = ifelse(data$bathroom_type %in% c("bath", "baths"),"bath", ifelse(data$bathroom_type %in% c("shared bath", "shared baths"), "shared", ifelse(data$bathroom_type  == "private bath", "private", NA))))

data <- data %>%
  mutate(f_bathroom_type = factor(bathroom_type))


numericals <- c("accommodates", "bedrooms", "beds", "minimum_nights", "maximum_nights", "availability_30", "availability_60","availability_90","availability_365", "number_of_reviews","number_of_reviews_ltm", "number_of_reviews_l30d", "review_scores_rating", 
                "calculated_host_listings_count", "calculated_host_listings_count_entire_homes", 
                "calculated_host_listings_count_private_rooms", "calculated_host_listings_count_shared_rooms", "reviews_per_month", "bathrooms")


data <- data %>%
  mutate_at(vars(all_of(numericals)), lst("n"=as.numeric))

nnames <- data %>%
  select(ends_with("_n")) %>%
  names()
nnames_i <- match(nnames, colnames(data))
colnames(data)[nnames_i] <- paste0("n_", numericals)


#create days since first review
data <- data %>%
  mutate(
    n_days_since = as.numeric(as.Date(calendar_last_scraped,format="%Y-%m-%d") -
                                as.Date(first_review ,format="%Y-%m-%d")))



#amenities is a list of stuff - use grepl to create dummies

data$essentials <- ifelse(grepl("Essentials",data$amenities),1,0)
data$tv <- ifelse(grepl("TV",data$amenities),1,0)
data$kitchen <- ifelse(grepl("Kitchen",data$amenities),1,0)
data$aircond <- ifelse(grepl("Air conditioning",data$amenities),1,0)
data$hairdry <- ifelse(grepl("Hair dryer",data$amenities),1,0)
data$heating <- ifelse(grepl("Heating",data$amenities),1,0)
data$hotwater <- ifelse(grepl("Hot water",data$amenities),1,0)
data$wifi <- ifelse(grepl("Wifi",data$amenities),1,0)
data$iron <- ifelse(grepl("Iron",data$amenities),1,0)
data$washer <- ifelse(grepl("Washer",data$amenities),1,0)
data$hangers <- ifelse(grepl("Hangers",data$amenities),1,0)
data$longterm <- ifelse(grepl("Long term stays allowed",data$amenities),1,0)
data$balcony <- ifelse(grepl("Patio or balcony",data$amenities),1,0)
data$parking <- ifelse(grepl("Free parking",data$amenities),1,0)
data$parking <- ifelse(grepl("Paid parking",data$amenities),1,0)
data$beachfront <- ifelse(grepl("Beachfront",data$amenities),1,0)
data$freezer <- ifelse(grepl("Freezer|Refrigerator",data$amenities),1,0)
data$kettle <- ifelse(grepl("Hot water kettle",data$amenities),1,0)
data$linens <- ifelse(grepl("Bed linens",data$amenities),1,0)
data$stove <- ifelse(grepl("Stove",data$amenities),1,0)
data$oven <- ifelse(grepl("Oven",data$amenities),1,0)
data$pool <- ifelse(grepl("Pool",data$amenities),1,0)
data$pillows <- ifelse(grepl("Extra pillows and blankets",data$amenities),1,0)
data$fireplace <- ifelse(grepl("Indoor fireplace",data$amenities),1,0)
data$microwave <- ifelse(grepl("Microwave",data$amenities),1,0)
data$workspace <- ifelse(grepl("Dedicated workspace",data$amenities),1,0)
data$cooking <- ifelse(grepl("Cooking basics",data$amenities),1,0)
data$dishes <- ifelse(grepl("Dishes and silverware",data$amenities),1,0)
data$coffee <- ifelse(grepl("Coffee maker",data$amenities),1,0)
data$hostgreets <- ifelse(grepl("Host greets you",data$amenities),1,0)
data$firstaid <- ifelse(grepl("First aid kit",data$amenities),1,0)
data$crib <- ifelse(grepl("Crib",data$amenities),1,0)
data$tub <- ifelse(grepl("Bathtub",data$amenities),1,0)
data$shades <- ifelse(grepl("Room-darkening shades",data$amenities),1,0)
data$backyard <- ifelse(grepl("Backyard",data$amenities),1,0)
data$elevator <- ifelse(grepl("Elevator",data$amenities),1,0)
data$bidet <- ifelse(grepl("Bidet",data$amenities),1,0)
data$wineglass <- ifelse(grepl("Wine glasses",data$amenities),1,0)
data$highchair <- ifelse(grepl("High chair",data$amenities),1,0)
data$bbq <- ifelse(grepl("BBQ grill",data$amenities),1,0)
data$smoke <- ifelse(grepl("Smoke alarm",data$amenities),1,0)
data$luggage <- ifelse(grepl("Luggage dropoff allowed",data$amenities),1,0)
data$toys <- ifelse(grepl("Children\\u2019s books and toys",data$amenities),1,0)

#convert booleans to dummies
data <- data %>% mutate_if(is.logical,as.numeric)

#dummies are the created variables and the booleans that were converted
dummies <- c(c("host_identity_verified", "host_is_superhost", "host_has_profile_pic", "has_availability", "instant_bookable"), names(data)[seq(105,146)])

data <- data %>%
  mutate_at(vars(dummies), funs("d"= (.)))
# rename columns
dnames <- data %>%
  select(ends_with("_d")) %>%
  names()
dnames_i <- match(dnames, colnames(data))
colnames(data)[dnames_i] <- paste0("d_", tolower(gsub("[^[:alnum:]_]", "",dummies)))

# keep columns if contain d_, n_,f_, p_, usd_ and some others
data <- data %>%
  select(matches("^d_.*|^n_.*|^f_.*|^p_.*|^usd_.*"), id)

```


```{r target engineering}

P95 <- function(x){quantile(x,0.95,na.rm=T)}
P05 <- function(x){quantile(x,0.05,na.rm=T)}

#datasummary( usd_price_day ~ Mean + Median + Min + Max + P05 + P25 + P75 + P95, data = data )

#maybe take log
data <- data %>%
  mutate(ln_usd_price_day = log(usd_price_day))

#filter on at least 5 USD, even for a room below that is unreasonably low
data <- data %>%
  filter(usd_price_day <1000 & usd_price_day >5)

```


```{r functional forms}
# Squares and further values to create
data <- data %>%
  mutate(n_accommodates2=n_accommodates^2, 
         ln_accommodates=log(n_accommodates) ,
         ln_accommodates2=log(n_accommodates)^2,
         ln_beds = log(n_beds),
         ln_number_of_reviews = log(n_number_of_reviews+1)
        )

# Pool accomodations with 0,1,2,10 bathrooms
data <- data %>%
  mutate(f_bathroom = cut(n_bathrooms, c(0,1,2,10), labels=c(0,1,2), right = F) )

# Pool num of reviews to 3 categories: none, 1-51 and >51
data <- data %>%
  mutate(f_number_of_reviews = cut(n_number_of_reviews, c(0,1,51,max(data$n_number_of_reviews)), labels=c(0,1,2), right = F))


# Pool and categorize the number of minimum nights: 1,2,3, 3+
data <- data %>%
  mutate(f_minimum_nights= cut(n_minimum_nights, c(1,2,3,max(data$n_minimum_nights)), labels=c(1,2,3), right = F))

#create same for maximum nights, 
data <- data %>%
  mutate(f_maximum_nights= cut(n_maximum_nights, c(7,15,31,365, max(data$n_maximum_nights)), labels=c(1,2,3,4), right = F))

#check host acceptance rate
#datasummary( p_host_acceptance_rate ~ Mean + Median + Min + Max + P05 + P25 + P75 + P95, data = data )

#replace 101% acceptance rate with 100%
data <- data %>%
  mutate(p_host_acceptance_rate = ifelse(p_host_acceptance_rate == 101, 100, p_host_acceptance_rate))


# Change Infinite values with NaNs
for (j in 1:ncol(data) ) data.table::set(data, which(is.infinite(data[[j]])), j, NA)

```

```{r dealing with NAs}
#check for number of missing values
#to_filter <- sapply(data, function(x) sum(is.na(x)))
#to_filter[to_filter > 0]

#drop if there would be na in target
data <- data %>%
  drop_na(usd_price_day)

#imput when few misssing values
data <- data %>%
  mutate(
    n_bathrooms =  ifelse(is.na(n_bathrooms), median(n_bathrooms, na.rm = T), n_bathrooms), #assume at least 1 bath
    n_beds = ifelse(is.na(n_beds), n_accommodates, n_beds), #assume n_beds=n_accomodates
    f_bathroom=ifelse(is.na(f_bathroom),1, f_bathroom),
    f_minimum_nights=ifelse(is.na(f_minimum_nights),1, f_minimum_nights),
    f_number_of_reviews=ifelse(is.na(f_number_of_reviews),1, f_number_of_reviews),
    ln_beds=ifelse(is.na(ln_beds),0, ln_beds),
    n_bedrooms = ifelse(is.na(n_bedrooms), n_beds, n_bedrooms), #assume n_bedrooms = n_beds
    d_host_has_profile_pic = ifelse(is.na(d_host_has_profile_pic), 0, d_host_has_profile_pic), #if no info on profile pic - good chance not there
    d_host_identity_verified = ifelse(is.na(d_host_identity_verified), 0, d_host_identity_verified),
    d_host_is_superhost = ifelse(is.na(d_host_is_superhost), 0, d_host_is_superhost)
  ) 

# drop the one column that has more than third its values NA - host response time
to_drop <- c("f_host_response_time")
data <- data %>%
  select(-one_of(to_drop))

#to_filter <- sapply(data, function(x) sum(is.na(x)))
#to_filter[to_filter > 0]

# replace missing variables re reviews with zero, when no review + add flags
data <- data %>%
  mutate(
    flag_days_since=ifelse(is.na(n_days_since),1, 0),
    n_days_since =  ifelse(is.na(n_days_since), median(n_days_since, na.rm = T), n_days_since),
    flag_review_scores_rating = ifelse(is.na(n_review_scores_rating),1, 0),
    n_review_scores_rating =  ifelse(is.na(n_review_scores_rating), median(n_review_scores_rating, na.rm = T), n_review_scores_rating),
    flag_reviews_per_month=ifelse(is.na(n_reviews_per_month),1, 0),
    n_reviews_per_month =  ifelse(is.na(n_reviews_per_month), median(n_reviews_per_month, na.rm = T), n_reviews_per_month),
    flag_n_number_of_reviews=ifelse(n_number_of_reviews==0,1, 0)
  )
#table(data$flag_days_since)

#drop if there are only a very little number of values missing (13 from more than 17000)
data <- data %>%
  drop_na(p_host_response_rate)

#correct missing categorical variables in f_maximum_nights
#View(data[is.na(data$f_maximum_nights),c("n_maximum_nights", "f_maximum_nights")])
data <- data %>%
  mutate(
    f_maximum_nights = ifelse(is.na(f_maximum_nights) & (n_maximum_nights < 7),1, ifelse(is.na(f_maximum_nights) & (n_maximum_nights == 222020), 4, f_maximum_nights)))


#if bathroom type na, put in simple category of bath
data$f_bathroom_type[is.na(data$f_bathroom_type)] <- "bath"

# Create variables, measuring the time since: squared, cubic, logs
data <- data %>%
  mutate(
    ln_days_since = log(n_days_since+1),
    ln_days_since2 = log(n_days_since+1)^2,
    ln_days_since3 = log(n_days_since+1)^3 ,
    n_days_since2=n_days_since^2,
    n_days_since3=n_days_since^3,
    ln_review_scores_rating = log(n_review_scores_rating),
    ln_days_since=ifelse(is.na(ln_days_since),0, ln_days_since),
    ln_days_since2=ifelse(is.na(ln_days_since2),0, ln_days_since2),
    ln_days_since3=ifelse(is.na(ln_days_since3),0, ln_days_since3),
  )

```

```{r final check and save clean data}
# Look at data
datasummary( id ~ N , data = data )
datasummary_skim( data , 'categorical' )


# where do we have missing variables now?
to_filter <- sapply(data, function(x) sum(is.na(x)))
to_filter[to_filter > 0]

# N=17350
write_csv(data, "./data/airbnb_sicily_clean.csv")

```

