---
title: "DA3 - Assignment 1"
author: "Adam Kovacs"
date: "1/21/2022"
output: pdf_document
---

## Introduction

In this project, I analyze the [**cps-earnings dataset**](https://osf.io/g8p9j/) to build predictive models targeting the earnings per hour of advertising, promotions, marketing and sales managers. Altogether 4 models are built, all OLS, but increasing in complexity. The performance of these models are evaluated through RMSE and BIC in the full sample and cross-validated RMSE. Finally, the relationship between model complexity and performance is illustrated with the help of a visual aid. 

Build four predictive models using linear regression for earnings per hour. 
1.	Models: the target variable is earnings per hour, all others would be predictors.
2.	Model 1 shall be the simplest, model 4 the more complex. It shall be OLS. You shall explain your choice of predictors.
3.	Compare model performance of these models (a) RMSE in the full sample, (2) cross-validated RMSE and (c) BIC in the full sample. 
4.	Discuss the relationship between model complexity and performance. You may use visual aids. 

```{r import, echo=FALSE, message=FALSE}
#clear memory
rm(list=ls())

#import packages
if (!require(pacman)){
  install.packages("pacman")
}

pacman::p_load(tidyverse, modelsummary, kableExtra, fixest, estimatr)

# import data
df_orig <- read_csv( 'https://osf.io/4ay9x/download' )

```

